### ISSUE TITLE
Update documentation comments

### ISSUE THREAD

**Issue by SametSahin10** [fuseio/fuse_wallet_sdk#25]
The method that work with the `WebSocket` now return a `Stream<SmartWalletEvent>` in the right side of `DC`. Update comments according to this.

**Comment by SametSahin10** [comment]
I've created this issue so that we don't forget to update documentation comments. We can work on it later. @LiorAgnin

**Comment by LiorAgnin** [comment]
@SametSahin10 I updated it.
