### ISSUE TITLE
Documentation for Building/Compiling

### ISSUE THREAD

**Issue by Mentors4EDU** [fuseio/fuse_wallet_sdk#46]
I haven't used Dart for a very long time and instructions on importing as well as building and compiling would be helpful. Also, where do you integrate your Fuse dev API keys? Which files?

**Comment by maorstamati** [comment]
Hey @Mentors4EDU, thanks for reaching out!
Have you checked our [documentation](https://docs.fuse.io/docs/developers/fuse-sdk/flutter-sdk/)? Please let me know if that helps.

**Comment by Mentors4EDU** [comment]
Hi, this should help. I can integrate it and setup the Dark dev environment and go from there.
